server: 
   port: 8082

spring: 
   application: 
      name: user-service


eureka: 
   client: 
      register-with-eureka: true
      fetch-registery: true
      service-url: 
         defaultZone: http://localhost:8761/eureka/
   instance: 
      hostname: localhost 